# secuencias_adn.py

secuencias_adn = {
    'León': 'ATGCAGCTAGCGTACGTAGCGTACGTAGCTAGCGTACGATCG',
    'Tigre': 'ATGCTAGCAGTACGATCGTAGCTAGCTAGCGTAGCTGACTG',
    'Elefante': 'ATGCGTACGTAGCTAGTGCATCGTAGCTAGCGTACGAGCTA',
    'Giraffa': 'ATGCATCGTACGTAGCATGACTGACGATCGTAGCTGATCG',
    'Cebra': 'ATCGTACGTAGCGTACGATGACTAGCATGCATGATCGTAGC',
    'Jirafa': 'ATGCATGAGTACGATCGTAGCATGACTGAGTCGATCGTAGC',
    'Lobo': 'ATGCGTAGCTAGATCGTAGCTAGCTAGCTAGCGTAGCATCG',
    'Oso': 'ATGCGTACGTAGCTAGCGTAGCTAGTACGTAGCTAGCGGCT',
    'Conejo': 'ATGCATGCAGTACGATCGTGCATCGTAGCAGCTAGTAGCG',
    'Lince': 'ATGCTAGCGTACGATCGTAGCTAGCGTAGCATGACTGCGT',
}
